In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
import sys, os
sys.path.append(os.path.abspath('..'))

In [7]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
df = pd.read_csv('../data/data.csv')
df['TransactionStartTime'] = pd.to_datetime(df['TransactionStartTime'], errors='coerce')

In [9]:
df.head(2)

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15 02:18:49+00:00,2,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15 02:19:08+00:00,2,0

In [10]:
from src.feature_engineering import AggregateFeature, ExtractFeature

INFO:root:Creating the AggregateFeature class
INFO:root:Creating the ExtractFeature class and initialize data

In [11]:
aggregate = AggregateFeature(df)

In [12]:
aggregate.aggregate('CustomerId', 'Value', 'sum', 'Total-Transaction-Amount')

INFO:root:Aggregating data based on specified column and operation
INFO:root:Performing insertion operation on specified column

In [13]:
aggregate.aggregate('CustomerId', 'Value', 'mean', 'Average-Transaction-Amount')

INFO:root:Aggregating data based on specified column and operation
INFO:root:Performing insertion operation on specified column

In [14]:
aggregate.aggregate('CustomerId', 'Value', 'count', 'Transaction-Count')

INFO:root:Aggregating data based on specified column and operation
INFO:root:Performing insertion operation on specified column

In [15]:
aggregate.aggregate('CustomerId', 'Value', 'std', 'Standard-Deviation-of-Transaction-Amounts')

INFO:root:Aggregating data based on specified column and operation
INFO:root:Performing insertion operation on specified column

In [16]:
df.head(2)

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,Standard-Deviation-of-Transaction-Amounts,Transaction-Count,Average-Transaction-Amount,Total-Transaction-Amount,TransactionStartTime,PricingStrategy,FraudResult
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2675.218372,119,1713.0,203847,2018-11-15 02:18:49+00:00,2,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2675.218372,119,1713.0,203847,2018-11-15 02:19:08+00:00,2,0

In [17]:
extract = ExtractFeature(df)

In [18]:
new_column = ['Transaction-Hour', 'Transaction-Day',
                      'Transaction-Month', 'Transaction-Year']
extract.extract_hr_to_year('TransactionStartTime', new_column)

INFO:root:Extracting hour from datetime column
INFO:root:Performing insertion operation on specified column
INFO:root:Performing insertion operation on specified column
INFO:root:Performing insertion operation on specified column
INFO:root:Performing insertion operation on specified column

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,...,Transaction-Count,Average-Transaction-Amount,Total-Transaction-Amount,TransactionStartTime,Transaction-Year,Transaction-Month,Transaction-Day,Transaction-Hour,PricingStrategy,FraudResult
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,...,119,1713.000000,203847,2018-11-15 02:18:49+00:00,2018,11,15,2,2,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,...,119,1713.000000,203847,2018-11-15 02:19:08+00:00,2018,11,15,2,2,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,...,2,500.000000,1000,2018-11-15 02:44:21+00:00,2018,11,15,2,2,0
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,...,38,7542.710526,286623,2018-11-15 03:32:55+00:00,2018,11,15,3,2,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,...,38,7542.710526,286623,2018-11-15 03:34:21+00:00,2018,11,15,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,256,ProviderId_4,ProductId_6,financial_services,...,573,4435.008726,2541260,2019-02-13 09:54:09+00:00,2019,2,13,9,2,0
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,256,ProviderId_6,ProductId_10,airtime,...,43,1467.837209,63117,2019-02-13 09:54:25+00:00,2019,2,13,9,2,0
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,256,ProviderId_4,ProductId_6,financial_services,...,43,1467.837209,63117,2019-02-13 09:54:35+00:00,2019,2,13,9,2,0
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,256,ProviderId_6,ProductId_19,tv,...,524,1906.246183,998873,2019-02-13 10:01:10+00:00,2019,2,13,10,2,0
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,256,ProviderId_4,ProductId_6,financial_services,...,524,1906.246183,998873,2019-02-13 10:01:28+00:00,2019,2,13,10,2,0

today drop 5 columns and use value instead of amount for total transaction amounts becuase it is absolute value of the amount

In [19]:
df = df.drop(['BatchId', 'AccountId', 'SubscriptionId', 'CurrencyCode', 'CountryCode', 'TransactionStartTime'], axis=1)

In [20]:
df.head(2)

,TransactionId,CustomerId,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,Standard-Deviation-of-Transaction-Amounts,Transaction-Count,Average-Transaction-Amount,Total-Transaction-Amount,Transaction-Year,Transaction-Month,Transaction-Day,Transaction-Hour,PricingStrategy,FraudResult
0,TransactionId_76871,CustomerId_4406,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2675.218372,119,1713.0,203847,2018,11,15,2,2,0
1,TransactionId_73770,CustomerId_4406,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2675.218372,119,1713.0,203847,2018,11,15,2,2,0

In [21]:
df.to_csv('../data/processed_data.csv', index=False)